import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { Transaction } from '../../src/db/schema'
import { format } from 'date-fns'
import { id as localeId } from 'date-fns/locale'

function formatIDR(amount: number): string {
  return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', minimumFractionDigits: 0 }).format(amount)
}

function buildPDF(title: string, subtitle: string, rows: Transaction[]): Buffer {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

  // Header
  doc.setFontSize(18)
  doc.setTextColor(255, 143, 171) // primary pink
  doc.text('Tabungan Lia', 14, 18)

  doc.setFontSize(12)
  doc.setTextColor(45, 45, 45)
  doc.text(title, 14, 27)
  doc.text(subtitle, 14, 34)

  // Table
  const tableBody = rows.map((t) => [
    format(new Date(t.transactionDate), 'dd MMM yyyy', { locale: localeId }),
    t.paymentMethod,
    formatIDR(t.amount),
    t.depositMessage ?? '-',
  ])

  const total = rows.reduce((sum, t) => sum + t.amount, 0)

  autoTable(doc, {
    startY: 42,
    head: [['Tanggal', 'Metode', 'Jumlah', 'Pesan']],
    body: tableBody,
    foot: [['', 'Total', formatIDR(total), '']],
    theme: 'striped',
    headStyles: { fillColor: [255, 143, 171], textColor: 255, fontStyle: 'bold' },
    footStyles: { fillColor: [255, 229, 236], textColor: [45, 45, 45], fontStyle: 'bold' },
    styles: { fontSize: 10, cellPadding: 3 },
    columnStyles: { 2: { halign: 'right' } },
  })

  // Footer
  const pageCount = (doc as any).internal.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150)
    doc.text(
      `Generated by Tabungan Lia — Halaman ${i} dari ${pageCount}`,
      14,
      doc.internal.pageSize.height - 8
    )
  }

  return Buffer.from(doc.output('arraybuffer'))
}

export function buildDailyPDF(date: string, rows: Transaction[]): Buffer {
  const displayDate = format(new Date(date), 'dd MMMM yyyy', { locale: localeId })
  return buildPDF('Laporan Harian', `Tanggal: ${displayDate}`, rows)
}

export function buildMonthlyPDF(year: number, month: number, rows: Transaction[]): Buffer {
  const displayMonth = format(new Date(year, month - 1, 1), 'MMMM yyyy', { locale: localeId })
  return buildPDF('Laporan Bulanan', `Bulan: ${displayMonth}`, rows)
}
